-- Close lifecycle recovery + full fee accounting + signal offer fields.
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "confirmBeforeOpen" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "active_positions" ADD COLUMN IF NOT EXISTS "finalizedAt" TIMESTAMP(3);
ALTER TABLE "active_positions" ADD COLUMN IF NOT EXISTS "entryFeeUsdt" DOUBLE PRECISION NOT NULL DEFAULT 0;

ALTER TABLE "order_history" ADD COLUMN IF NOT EXISTS "grossPnl" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "order_history" ADD COLUMN IF NOT EXISTS "entryFeeUsdt" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "order_history" ADD COLUMN IF NOT EXISTS "exitFeeUsdt" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "order_history" ADD COLUMN IF NOT EXISTS "positionId" TEXT;
CREATE UNIQUE INDEX IF NOT EXISTS "order_history_positionId_key" ON "order_history"("positionId");

ALTER TABLE "signals" ADD COLUMN IF NOT EXISTS "riskReward" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "signals" ADD COLUMN IF NOT EXISTS "factorsJson" TEXT NOT NULL DEFAULT '[]';
ALTER TABLE "signals" ADD COLUMN IF NOT EXISTS "sizeUsdt" DOUBLE PRECISION;
ALTER TABLE "signals" ADD COLUMN IF NOT EXISTS "marginUsdt" DOUBLE PRECISION;
ALTER TABLE "signals" ADD COLUMN IF NOT EXISTS "leverage" INTEGER;
ALTER TABLE "signals" ADD COLUMN IF NOT EXISTS "quantity" DOUBLE PRECISION;
ALTER TABLE "signals" ADD COLUMN IF NOT EXISTS "maxRiskUsdt" DOUBLE PRECISION;
ALTER TABLE "signals" ADD COLUMN IF NOT EXISTS "potentialProfitUsdt" DOUBLE PRECISION;
ALTER TABLE "signals" ADD COLUMN IF NOT EXISTS "expiresAt" TIMESTAMP(3);
